### ISSUE TITLE
Does not seem to work with the MKR1000

### ISSUE THREAD

**Issue by AugustoEst** [sparkfun/SparkFun_ToF_Range_Finder-VL6180_Arduino_Library#4]
The library does not work with the MKR1000. The code compiles fine, but after it's uploaded into the board, it makes it disappear from the list of USB devices available.

I'm using the Arduino IDE _1.6.11_, and the latest version of the library. I'm also using SparkFun's VL6180 sensor board (_SEN-12785_).

**MKR1000-VL6180**
5V-VCC
GND-GND
SCL-SCL
SDA-SDA

**Comment by Grahldg** [comment]
Hi @AugustoEst ,

Sorry for the late reply.  In general for more immediate responses it is best to contact our [Technical Assistance Team](https://www.sparkfun.com/technical_assistance).  It appears that numerous people have had similar issues with the MKR series with various sketches.  I would want to verify that this is in fact a problem with the library before making any changes.  Are you still experiencing issues with this?

**Comment by nseidle** [comment]
Closing stale issues. Please re-open if this is still an issue.
